version: '3.8'
services:
  neo4j:
    image: neo4j:5.14.0-community
    expose:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - data-volume:/data
      - logs-volume:/logs
  nuxt-app:
    build:
      context: .
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - neo4j

volumes:
  data-volume:
  logs-volume:
