version: '3.8'
services:
  neo4j:
    image: neo4j:5.14.0-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testtesttest
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
  nuxt-app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=testtesttest
      - NEO4J_URI=bolt://neo4j:7687

