version: '3.8'
services:
  neo4j:
    image: neo4j:5.14.0-community
    ports:
      - '127.0.0.1:7687:7687'
    environment:
      - NEO4J_AUTH=none
    volumes:
      - data-volume:/data
      - logs-volume:/logs

  nuxt-app:
    build:
      context: .
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - neo4j
    command: >
      bash -c "npm run start & ./wait-for-it.sh neo4j:7687 --timeout=30 -- npm run seed && while :; do sleep 1; done"
volumes:
  data-volume:
  logs-volume:
